name = 'VIDEO_UPLOADER'
secure = "http"
host = 'spongebob'
server = "localhost"
port = 8081
curl_limit_rate = "10M" # 10K slow enough / 10M
video_group = "youtube"
upload_path = "/video/upload"

# via fn download
#player_path = "/video/download" 
# via fn play -> Bytes
player_path = "/video/play"

video_dir = "/home/conan/video/youtube"

#limit number of <Vec<Video>> uploaded to speed up debug
sample_limit_start = 0 # 0 # 12
sample_limit_end = -1 # -1 no limit # 20 

html_path = "/home/conan/soft/rust/handler_video/html/"
html_template = "<html>\n\t<body>\n\t<p>handler_video</p>\n\t<p>\n\t\t{all_videos}\n\t</p>\n\t</body>\n</html>"

#+type
video_tag = "\n\t\t<p><i>{name}</i></p>\n\t\t<video width={width} controls autoplay muted>\n\t\t\t<source src={src} type=\"{type}\"/>\n\t\t</video>"
#-type
#video_tag = "\n\t\t<p><i>{name}</i></p>\n\t\t<video width={width} controls autoplay muted>\n\t\t\t<source src={src}/>\n\t\t</video>"

player_width = "640"
content_type = "video/mp4" # not reading via metadata just testing with videos
#content_type = ""
#content_type = "application/octet-stream" 

[flag]
debug_config = false
debug_template = false
