name = 'HANDLER_CONTENT'
host = 'spongebob'
server = "localhost"
port = 8081
workers = -1 # 2 # 64 # -1 as default cpu number
log_format = "\"%r\" %s %b \"%{User-Agent}i\" %D"

[flag]
debug_config = true # false
