[package]
name = "web-app-ssr"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.actix-web]
#version = "3"
version = "4.0.1"

[dependencies.actix-files]
#version = "0.5.0"
version = "0.6.0"
