name = 'HANDLER_VIDEO'
host = 'spongebob'
#server = "127.0.0.1"
#server = "localhost"
server = "192.168.0.103"
port = 8081
workers = 4
static_dir = "/home/conan/soft/rust/handler_video/storage/"
log_format = "\"%r\" %s %b \"%{User-Agent}i\" %D"

[flag]
debug_config = false
#verify dir is available and we can write before each video safe	     
verify_dir_per_video = true # false
