user = 

name = 
host = 
work_dir = 

[broker]
[broker.lord]
machine = 
client_id = 
interval = 

username = 
password = 

#debug = true #false
debug = false

[broker.metynka]
machine = 
client_id = 
interval = 

username = 
password = 

#debug = true #false
debug = false

[flag]
# display this config file
debug_config = false
