user = "lib_test_sonya"

name = 'easy_laptop'
host = 'spongebob'
work_dir = '/home/conan/soft/rust/lib_test'

[broker]
machine = "tcp://jozefina:1883"
client_id = "SPONGEBOB_RUST_L"
interval = 20

username = "lord"
password = "lord"

#debug = true #false
debug = false

[flag]
# display this config file
debug_config = false
