[package]
name = "websocket"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "websocket-server"
path = "src/main.rs"

[[bin]]
name = "websocket-client"
path = "src/client.rs"


[dependencies]
env_logger = "0.9"
log = "0.4"

actix = "0.13"
actix-codec = "0.5"
actix-files = "0.6"
actix-rt = "2"
actix-web = "4"
actix-web-actors = "4.1"
awc = "3.0.0-beta.21"


[dependencies.futures-util]
version = "0.3.7"
default-features = false
features = ["std", "sink"]

[dependencies.tokio]
version = "1.13.1"
features = ["full"]

[dependencies.tokio-stream]
version = "0.1.8"
